### ISSUE TITLE
Would be nice to have Markdown support

### ISSUE THREAD

**Issue by emptymalei** [hashashin/ksp_notes#4]
This is really a nice mod. I love it. I use it a lot it and it saves me tons of time. I am thinking, would it be cool to integrate markdown (github flavored for example)?

**Comment by hashashin** [comment]
Hi, I can go the easy way by just enabling rich text support in the text area. Unity support that but it's disabled by default. I don't want to make this plugins more complex and neither have skills to, I've to be honest about this hehe. Can you please test the pre-release here?: https://github.com/hashashin/ksp_notes/releases/download/0.12.1/notes-0.12.1.zip
And here what it's supported: http://docs.unity3d.com/Manual/StyledText.html

Awaiting feedback, thanks.

Salud.

**Comment by emptymalei** [comment]
Wow it works pretty good.

![image](https://cloud.githubusercontent.com/assets/663798/10271911/8f0c1c80-6ad5-11e5-8291-dd25b9ff5bdd.png)

Thank you for this work.

**Comment by hashashin** [comment]
I'll promote this build to release then, thanks you for the feedback!

Salud.
